### ISSUE TITLE
Resting heading based on starting position

### ISSUE THREAD

**Issue by hamster1147** [mjansen4857/PathPlanner#10]
Currently the heading is always based on the field which sometimes isn't true during competition. Would be useful to have the heading for the whole path be based on the starting position's direction.

Example: If I decide to start the robot pointing down the screen relative to the program's drawing, the path would generate starting at a heading of 0 and increment and decrement from their.

Instead what happens is the robot immediately tries to turn 90 degrees and then starts going the wrong direction.

**Comment by mjansen4857** [comment]
Added this an an output format option. Using an uppercase H instead of lowercase will give a relative heading, so the start of the path will be 0 degrees.

**Comment by hamster1147** [comment]
You're the best.
