### ISSUE TITLE
Better marker time calculation?

### ISSUE THREAD

**Issue by bckircher** [mjansen4857/pathplanner#105]
The current marker time calculation involves looping over every state of the generated trajectory to find the one that is closest in x/y position to each marker. Not only is this slow (as recognized in the code comments!), but it will produce incorrect/unpredictable results if a trajectory consists of several waypoints that result in an overlapping trajectory (sure, perhaps this is a bit of an exceptional case, but I think it becomes more realistic with the ability to use markers to trigger events along the path following and possibly an amenable autonomous game setup).

Since the markers are defines as the "percentage" of the way along a trajectory, wouldn't this be the same as the computed trajectory state at the same "percentage" of the way along the states?

Take a simple path that has just a starting and ending waypoint. The states are computed by finding the N points that are "equally spaced" along the cubic bezier (i.e. computed using equally spaced values of _t_). For a marker placed at 0.5 along that path, the same cubic bezier is used with _t_ set to 0.5 to find the marker position.

Seems like given the step value for _t_, the two states on either side of a marker can be trivially found (by direct index computation), then either the closest or a quick lerp used...for the position in the GUI or for the time in robot code.

Of course, this becomes slightly trickier for a trajectory with more than two waypoints...but not very much (the first N states correspond to the trajectory between waypoints 1 and 2, the next N states are between waypoint 2 and 3, etc.; being careful to observe the N-1 nature since the last state of the first segment is the same as the first state of the second segment).

Have I reasoned this out correctly? Or am I missing something? If I have this right, I'm happy to develop/test the code and submit a PR.

**Comment by mjansen4857** [comment]
I believe that sounds correct. I forgot at the time that each segment of a path has a fixed number of states. Older versions used to split states by time so the number per segment was variable. 

A really simple solution I could think of would just take the `waypointRelativePos` of the event marker and multiply it by the number of states per segment (found by `1.0 / PathPlanner.resolution`) and either round that to get the index of the corresponding state, or lerp between the 2 closest states.

So for example, in a path with 3 waypoints (2 segments) and a marker with a position of 1.5 (halfway between the second and third waypoint):
`i = 1.5 * (1.0 / PathPlanner.resolution (default 0.004)) = 375`

Feel free to take this on if you'd like.
