### ISSUE TITLE
PathPlanner doesn't recover from failing to open a project

### ISSUE THREAD

**Issue by Ashray-g** [mjansen4857/pathplanner#116]
The application opens blurry on mac (tried download from git multiple times and app store a couple times)

<img width="1280" alt="Screen Shot 2022-09-23 at 10 04 00" src="https://user-images.githubusercontent.com/43589795/192014190-fa914c98-297d-4970-8b45-b809d9aa63d1.png">

**Comment by mjansen4857** [comment]
Is this the first time you’ve used the app or has it worked fine before?

**Comment by Ashray-g** [comment]
It worked fine all year for us until about a week ago.

**Comment by mjansen4857** [comment]
My guess then is that one of your path files is malformed and causing a crash. Try removing all of the paths from the project you had opened then see if it opens up fine. If so you can try slowly adding paths back until it fails to open again or just open them in notepad and see if there’s anything obvious.

**Comment by Ashray-g** [comment]
Oh I might have also moved my main project folder to a different directory. Maybe it's having trouble since it's not where it was anymore?

**Comment by Ashray-g** [comment]
Since I deleted + reinstalled the app why would it have the information on what project I'm currently using?

**Comment by mjansen4857** [comment]
That would make sense. It will try to open the last folder that was opened so if that doesn’t exist anymore that could cause issues. If that ends up being the case I’ll switch this issue to making changes to allow the app to recover from failing to open a project. Uninstalling the app doesn’t actually remove the file that the settings are stored in. I don’t remember the exact path for the file. I’ll look for it.

**Comment by Ashray-g** [comment]
Oh, awesome! Thanks for the insanely quick reply, we have chezy today actually and I just remembered to do this in case we need to make changes there.

**Comment by Ashray-g** [comment]
Is it the plist file in Library/Preferences?

**Comment by mjansen4857** [comment]
Run this in terminal: `defaults delete com.mjansen4857.pathplanner flutter.currentProjectDir`

**Comment by Ashray-g** [comment]
Awesome! That worked

**Comment by mjansen4857** [comment]
Great. I'll use this issue to fix it crashing then.
