### ISSUE TITLE
Getting Errors trying to load paths

### ISSUE THREAD

**Issue by J-Barta** [mjansen4857/pathplanner#124]
We're trying to generate trajectories, but getting the errors shown in the image. We have no idea why and are in desperate need of help (we have 3 days until comp)
![image_2022-10-19_183058302](https://user-images.githubusercontent.com/53406552/196816892-b9acb847-7ab6-4222-b20a-3b040ce274b6.png)
![20221019_182109](https://user-images.githubusercontent.com/53406552/196816895-926e5e3c-6c54-45f1-b9e1-0c58631ee1d1.jpg)

**Comment by mjansen4857** [comment]
Try manually editing the files and add `.0` behind every whole number that doesn't already have it. Never seen the library care before so not sure why that's going on.

**Comment by J-Barta** [comment]
We are using an unreleased version because we have no choice. The 2022 release doesn't work on my computer and won't launch on our windows 10 machine. There are no integers in the JSONs to add anything to

**Comment by mjansen4857** [comment]
Could you send over the path file you are trying to load?

**Comment by mjansen4857** [comment]
Are you using unreleased PPLib as well or is that 2022? This seems to be fixed in the master branch. You can copy the source [here](https://github.com/mjansen4857/pathplanner/tree/main/pathplannerlib/src/main/java) into your robot code project and use that instead of the vendordep.

**Comment by J-Barta** [comment]
Throws the same error

**Comment by mjansen4857** [comment]
Did you uninstall the vendordep? It could still be using that instead. If so, can you send the stack trace again?

**Comment by J-Barta** [comment]
I did uninstall the vendordep, and it doesn't even send a stack trace half the time, it just starts spamming the console with every state of every trajectory and never actually loads them

**Comment by mjansen4857** [comment]
That might be [this line](https://github.com/CCShambots/Shambots5907_22O/blob/AllBotCode/src/main/java/frc/robot/util/RobotManager.java#L290) or somewhere else if you have other print statements. PPLib doesn't print to the console.

**Comment by J-Barta** [comment]
We're definitely not printing out the information it's sending. I'm reflashing the rio now to see if that helps with anything, but I'll send you an image of what it's sending once it finishes

**Comment by mjansen4857** [comment]
Did removing that print statement solve the issue?

**Comment by J-Barta** [comment]
Yes, that was my bad

**Comment by mjansen4857** [comment]
Ok, no problem. Glad to hear its working. I'm going to close this issue then, feel free to open another one if you come across any other issues. I'm hoping to get an initial beta release out in the next few days so you can use that instead of copying the source.
