### ISSUE TITLE
No live view for marker

### ISSUE THREAD

**Issue by laviRZ** [mjansen4857/pathplanner#134]
When placing a new marker, I don't see the orange marker in real time before placing the marker. Only after adding it it shows and then I can change its position and see where it will be.

**Comment by mjansen4857** [comment]
Drawing a marker that doesn't actually exist could be a bit confusing, so this was left out. Some sort of preview could be helpful though, so I can draw an orange dot or something instead of a whole marker.

**Comment by laviRZ** [comment]
Maybe half transparent?
