### ISSUE TITLE
Markers list

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#138]
create a list of markers (per project, not per path), then in the markers editor you can choose a marker from a dropdown or just type a new name.

The reason is to prevent typos/inconsistencies in markers name, and reduce the chances of incompatibility with robot code.
(E.g., having multiple usages of “Open Intake” marker)

**Comment by mjansen4857** [comment]
I think rather than adding this now just to re-do it again later I'm going to hold off for next year. I want to re-work the markers UI to feel like a GUI tool for planning autonomous modes. This will be included with that. Too big of a job for this season which is why I say next year.
