### ISSUE TITLE
App not opening on Windows 11

### ISSUE THREAD

**Issue by pratyush-p** [mjansen4857/pathplanner#141]
I downloaded the app from both the Microsoft store, as well as the manual .zip installation. It is not opening from either place. My cursor  shows the blue circle loading icon for about half a second and then nothing happens. I am not able to replicate this issue on any Windows 10 machines.

**Comment by mjansen4857** [comment]
Did you download the 2023 beta version? This sounds like a duplicate of #117 which is fixed.

**Comment by pratyush-p** [comment]
I am using 2023.0.1 pathplanner lib, but only 2023.0.0 is working. 2023.0.1 doesn't work still

**Comment by pratyush-p** [comment]
wait nvm it works now sry mb.
