### ISSUE TITLE
Robot dimensions not saved in 2023.1.0 beta

### ISSUE THREAD

**Issue by legoguy1000** [mjansen4857/pathplanner#162]
Using the beta version 2023.1.0, when I change the dimensions of the robot in the UI, it doesn't save on close.

**Comment by mjansen4857** [comment]
You need to hit enter every time you change a value. Are you doing that?

**Comment by legoguy1000** [comment]
nope and that worked. My bad :(.  Is that documented somewhere? maybe a tooltip or a note underneath saying that?

**Comment by mjansen4857** [comment]
It might be mentioned on the wiki somewhere. I could make the "close" button save these fields at some point.
