### ISSUE TITLE
[REQUEST] Import custom field picture

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#17]
Having the ability to import and use a custom field picture.

**Comment by mjansen4857** [comment]
At this point, the code for this app is so messy that I'd need to rewrite a significant portion of the app to do this in a way I'd be happy with. I'm going to close this issue for now since I don't want to take on a rewrite yet. If/when I decide to do a full rewrite this will be included with it.

**Comment by memtech3** [comment]
Any updates on this?
