### ISSUE TITLE
Crash when "Deploy" is clicked while not connected to Robot

### ISSUE THREAD

**Issue by itsmichaelyu** [mjansen4857/pathplanner#188]
The entire program just caches when "Deploy" is clicked, it would be nice to prompt the user with an error instead.

**Comment by mjansen4857** [comment]
There already is an error prompt built into flutter but it misses a lot unfortunately. What platform are you running on and where did you install from? It’s likely there’s no permissions to run console commands so that feature should just be disabled for those builds.

**Comment by itsmichaelyu** [comment]
I'm on macOS 13.1 x64 with PathPlanner v2023.2.0 from the app store.

**Comment by mjansen4857** [comment]
Yeah that shouldn’t even be visible in the App Store build. I’ll look into why that is still there. If you really want to use that feature you’ll need to download the version from GitHub
