### ISSUE TITLE
[REQUEST] flipPath button

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/PathPlanner#19]
Having a button that will flip a path from right to left (/left to right).
(For example, flipping "2019 right rocket hatch" mode to "left rocket hatch").

**Comment by lidor51** [comment]
To ease it,
For every point:
flippedPt=(X, fieldWidth-Y, -angle)

**Comment by mjansen4857** [comment]
Added in 3e325db

In an effort to avoid clutter there is a keyboard shortcut instead of a button. Ctrl+Shift+X and Ctrl+Shift+Y to flip in the X and Y direction respectively.
