### ISSUE TITLE
Latest build has all white screen on Edit Markers

### ISSUE THREAD

**Issue by WarrenReynolds** [mjansen4857/pathplanner#190]
Hi,
The latest build seems to have an issue on windows.

[https://github.com/mjansen4857/pathplanner/actions/runs/3795324124](https://github.com/mjansen4857/pathplanner/actions/runs/3795324124)

When you click edit markers you get an all white screen.  Tried building from source and also running the version created in Actions on the last Pull Request.

**Comment by mjansen4857** [comment]
Was an issue with paths with 0 markers. For some reason I never thought to test that lol. Thanks for the find.
