### ISSUE TITLE
Holonomic angle seems to have no effect

### ISSUE THREAD

**Issue by nailuj29** [mjansen4857/pathplanner#200]
My team has been using Pathplanner to create swerve drive autonomous modes, and it seems like the Holonomic angle field is doing nothing. We created a path with a changing Holonomic angle throughout the path, and our robot remains facing the same direction throughout the path. I can provide our code and paths along with a few videos during our meeting tomorrow.

**Comment by mjansen4857** [comment]
Feel free to post code here if you want, but we can just continue the discussion on CD if you'd prefer as this likely isn't a PP bug. I'll leave the issue open just in case though.
