### ISSUE TITLE
PathPlanner Immediately quits itself on M1 Mac

### ISSUE THREAD

**Issue by team3572** [mjansen4857/pathplanner#210]
Downloaded from App Store.
Launch, see a window for a micro second then the app quits.
I don't think it crashes because I don't get a crash window.

I had an old version installed from 2020, it is possible there is a cache folder or something I'd need to delete to get the new version running?

**Comment by team3572** [comment]
Some messages from the console...
error	11:28:16.470345-0500	PathPlanner	cannot open file at line 45530 of [9ff244ce07]
error	11:28:16.470355-0500	PathPlanner	os_unix.c:45530: (2) open(/var/db/DetachedSignatures) - No such file or directory
default	11:28:16.479386-0500	PathPlanner	Entering exit handler.

**Comment by mjansen4857** [comment]
I'm able to launch it when installed from the app store so not sure what's wrong on your end. Does it work if you download from github?

**Comment by team3572** [comment]
So after getting a bunch of stuff installed (ruby, cocoapods, Flutter). I was able to build it from the repository using Flutter and the build version worked.
For me, the app store version still simply quits.
So I'm ok with this since I can getting it working but if you want anymore info from me on the app store version like a log or something please let me know.

**Comment by mjansen4857** [comment]
Yeah I can't really find anything relevant from the console output you provided. There was an update yesterday, did you update your app store version to that?

Also, there are mac builds in the github releases and github actions if you prefer to not build it manually all the time.

**Comment by cpostbitbuckets** [comment]
One of my students was having this problem. Pathplanner was crashing on his M1 while trying to read secure bookmarks.

https://github.com/mjansen4857/pathplanner/blob/main/lib/pages/home_page.dart#L79

We deleted the preferences from last season's pathplanner by executing this in the terminal: `defaults delete com.mjansen4857.pathplanner`

Now it launches.

**Comment by mjansen4857** [comment]
@team3572 perhaps give that a try. It may be a different issue if your most recent version before this one was from 2020, which didn’t use secure bookmarks or defaults at all. Worth a try though.

**Comment by aliddy23** [comment]
> We deleted the preferences from last season's pathplanner by executing this in the terminal: `defaults delete com.mjansen4857.pathplanner`

This worked for me as well.

**Comment by team3572** [comment]
Worked. Thanks.

**Comment by mjansen4857** [comment]
Awesome. I think I know what is specifically causing the crash, so I will leave this issue open to try and catch that issue to prevent it from crashing. It happens when the project you previously had open doesn't exist anymore. Fixed this issue earlier for other platforms but macOS needs to access secure bookmarks to read the files in the directory so it can crash there too I guess.

**Comment by Chris2fourlaw** [comment]
Unable to reproduce with MacBook Pro 16 in, 2021, M1 Pro

**Comment by Savimaster** [comment]
> 

This worked for me as well

**Comment by Savimaster** [comment]
> One of my students was having this problem. Pathplanner was crashing on his M1 while trying to read secure bookmarks.
> 
> https://github.com/mjansen4857/pathplanner/blob/main/lib/pages/home_page.dart#L79
> 
> We deleted the preferences from last season's pathplanner by executing this in the terminal: `defaults delete com.mjansen4857.pathplanner`
> 
> Now it launches.

This also worked for me.
