### ISSUE TITLE
Issue with Y value in resetPose

### ISSUE THREAD

**Issue by EddieDL** [mjansen4857/pathplanner#214]
I know there is an update that isn't yet in a release to fix issues where the red alliance pose reset is not correct. However, I am having a problem on the Blue side.

When I use the attached path, the resetPose call is passed a pose with the following values:
x: 1.8
y: 7.59
rot: 0

I believe I have configured the auto path on the blue alliance, but am confused why it is passing a different y than what is configured in the path file.

Perhaps the latest update fixes this issue as well?

[Uploading Straight Test.json…]()

**Comment by EddieDL** [comment]
{
  "waypoints": [
    {
      "anchorPoint": {
        "x": 1.8,
        "y": 0.43
      },
      "prevControl": null,
      "nextControl": {
        "x": 2.8,
        "y": 0.43
      },
      "holonomicAngle": 0.0,
      "isReversal": false,
      "velOverride": null,
      "isLocked": false,
      "isStopPoint": false,
      "stopEvent": {
        "names": [],
        "executionBehavior": "parallel",
        "waitBehavior": "none",
        "waitTime": 0
      }
    },
    {
      "anchorPoint": {
        "x": 2.8,
        "y": 0.43
      },
      "prevControl": {
        "x": 1.7999999999999998,
        "y": 0.43000000000000016
      },
      "nextControl": null,
      "holonomicAngle": 180.0,
      "isReversal": false,
      "velOverride": null,
      "isLocked": false,
      "isStopPoint": false,
      "stopEvent": {
        "names": [],
        "executionBehavior": "parallel",
        "waitBehavior": "none",
        "waitTime": 0
      }
    }
  ],
  "markers": []
}

**Comment by mjansen4857** [comment]
The update was released. 2023.3.1.

Did you set your alliance color to blue in the driver station?

**Comment by EddieDL** [comment]
From what I can tell the latest version is missing 2 commits. One of which is the fix for the pose reset.

No matter what side I have selected the y value passed in is the same.

**Comment by mjansen4857** [comment]
The releases on this repo are unrelated to PPLib releases. 

Anyways, found the issue in the code. Will push another update tonight

**Comment by EddieDL** [comment]
Oh I didn't realize that. Good to know.

Thanks for looking at it quickly. I am just happy that it means my code might not be broken :)

**Comment by mjansen4857** [comment]
Ok update pushed. Are you able to confirm if the problem is fixed?

**Comment by EddieDL** [comment]
I can't check tonight. I might be able to test tomorrow. If not it will be Monday :( Sorry

**Comment by mjansen4857** [comment]
No problem. Just want to make sure that the issue that was fixed is what was causing your problem. Pretty sure it is, but I don’t want to leave you hanging if not.

**Comment by EddieDL** [comment]
I can confirm that your latest fix addressed my issue. Thanks for investigating and resolving.
