### ISSUE TITLE
Could not find pathplanner 2023.3.1

### ISSUE THREAD

**Issue by Teddy-Mengistie** [mjansen4857/pathplanner#219]
This issue just started happening, I have used this version before and it is weird that it cannot find pathplanner anymore.
![image](https://user-images.githubusercontent.com/55628361/212580761-b44302ac-cfde-4b0f-97eb-f04c4852e35a.png)

**Comment by mjansen4857** [comment]
I deleted that version because it has a fairly significant bug so I wanted to make sure people don't use it. Upgrade to either 2023.3.2 or 2023.3.3.

I'll pin this so others who run into this can see this.

**Comment by Teddy-Mengistie** [comment]
alright, thank you for clarifying :)
