### ISSUE TITLE
Odometry reset to the wrong pose when useAllianceColor is false

### ISSUE THREAD

**Issue by ErikCald** [mjansen4857/pathplanner#220]
I'm in Java, using SwerveAutoBuilder. When useAllianceColor is false, it's resetting odometry to the wrong pose.

I think I traced the issue to the resetPose method in BaseAutoBuilder which is transforming the initalState based on the alliance color even if useAllianceColor is false.

**Comment by mjansen4857** [comment]
Yeah you're right. Oops. Will push an update to fix that later today.

**Comment by mjansen4857** [comment]
Update is currently being deployed. Thanks for the report
