### ISSUE TITLE
deploy updated path to roboRIO without re-deploying robot code

### ISSUE THREAD

**Issue by gcschmit** [mjansen4857/pathplanner#223]
When iterating on an auto path, it would be useful to be able to deploy the updated path to the roboRIO without re-deploying the robot code and waiting for that process to complete. In our robot code, we would need to reload our paths as that is usually only done when the RobotContainer is constructed, but that additional complexity would probably be worth the trouble. (I naively thought that PathPlannerServer helped with this, but now that I took the time to read the wiki I know better.)

Probably not something for this season but perhaps to consider in the future.

**Comment by mjansen4857** [comment]
So you're asking for the paths to regenerated when PathPlannerServer updates them so you don't need to reload code? Because it already handles deploying updated paths so I'm assuming that's what you mean.

**Comment by gcschmit** [comment]
Sounds like we need to spent more time with PathPlannerLib Server. If we enable PathPlannerLib Server and connect PathPlanner to it, and change a path in PathPlanner, is that change reflected on the robot and would be reflected the next time we run an auto path? (We subclass PPSwerveControllerCommand.)

**Comment by gcschmit** [comment]
We enabled PathPlannerLib Server and explored it this morning. It is awesome and does exactly what we want. I was focused on the visualization of the trajectory and pose and missed the deploy feature.
