### ISSUE TITLE
Add wheel speed setpoints / ChassisSpeeds to network tables

### ISSUE THREAD

**Issue by edf42001** [mjansen4857/pathplanner#224]
In `PPRamseteCommand`, do you think it would be useful to add `leftSpeedSetpoint`, `rightSpeedSetpoint`, as well as the `ChassisSpeeds`' `vxMetersPerSecond`, `vyMetersPerSecond`, and `omegaRadiansPerSecond` to SmartDashboard? This would allow teams to plot these setpoints vs the actual values measured from the robot, in order to verify and tune feedforward / DiffDriveKinematics gains and velocity PID loops.

**Comment by mjansen4857** [comment]
I think it’s best to leave this up to the user, since these values are already passed through the output methods. So, you could just add these set points to SD in your output methods.

**Comment by edf42001** [comment]
Which output methods? I tried to find a way to access the values, but they look to be locked up inside the implementation of the command (such as on these lines): https://github.com/mjansen4857/pathplanner/blob/00920e70c41642f82fae201eec277cf79190daf0/pathplannerlib/src/main/java/com/pathplanner/lib/commands/PPRamseteCommand.java#L292-L293

**Comment by mjansen4857** [comment]
You should be able to use your kinematics to convert from left and right speeds to ChassisSpeeds (if diff. drive kinematics are anything like SwerveDriveKinematics, not 100% sure on that)

I am in the middle of working on a way to add custom logging callbacks to the path following commands, so I can potentially add another one for ChassisSpeeds setpoints too

**Comment by edf42001** [comment]
Thanks for the workaround. Having the ability to access these setpoints without duplicating code or backtracking calculations will be great. I look forward to the custom callbacks.
