### ISSUE TITLE
PathPlanner Command trajectory mirroring behavior should not be enabled by default 

### ISSUE THREAD

**Issue by jonathandao0** [mjansen4857/pathplanner#228]
Currently, PathPlanner Commands will flip a trajectory based on the alliance color defined by the DriverStation software. The library should not enable this behavior by default and it should only be enabled if the user explicitly adds it to PathPlanner Command constructors. The behavior as-is can lead to a confusing and frustrating user experience.

A few points related to this:
- When starting autonomous development, teams generate simple autonomous paths to verify basic functionality/accuracy, such as driving straight or making a simple spline curve. In this case, teams are probably not enforcing proper placement of trajectory points based on the field image. This can lead to needless confusion by teams when testing out the PathPlanner software on their robots. There seems to already be several issues reported by teams on ChiefDelphi with PathPlanner that may be related to this.
- You are instructing teams to base all of their autonomous paths on the Blue side of the field so that they are properly mirrored by PathPlanner Commands ([2023 Warning](https://github.com/mjansen4857/pathplanner/blob/036cef63a157317d8eefee70531f26a2880e096b/lib/pages/home_page.dart#L149)). The FRC DriverStation software by default sets the player station to Red 1, so novice teams are likely to encounter issues with path following because changing the alliance color in the DriverStation software is not normally done when testing autonomous routines. Additionally, the warning message appears only once on initial launch of the PathPlanner GUI, so it can be easily ignored and forgotten.
- This behavior needlessly breaks backwards compatibility with older software. If I wanted to upgrade code from a 2022 robot to work with the 2023 WPILib software/RoboRIO image, I would need to update all PathPlanner Command calls to explicitly not mirror the auto paths, as the field that year was diagonally symmetric and did not require teams to mirror their paths.
- The behavior as implemented is hard to maintain for future FRC games due to future fields potentially having different symmetries. It does not make sense for the default PathPlanner Command behavior to change based on year-specific differences. 
- The DriverStation.reportWarning() calls within the PathPlanner Commands are not sufficient enough to prevent user error. The DriverStation Log console is already crowded with many other warning/information statements, so this warning can easily be missed by teams.
- The PathPlanner Commands send a Field2D object with a visualization of the trajectory that is actually followed using the SmartDashboard interface. This can be another way to determine if a PathPlanner Command is flipping the trajectory. However, the Field2D object does not display properly through Shuffleboard, which also uses the SmartDashboard interface. An additional signal sent by PathPlanner Commands such as a Boolean that indicates if a trajectory is flipped can make it easier to identify this behavior.

**Comment by mjansen4857** [comment]
You're probably right. My thoughts on having it enabled by default was for the teams that do ignore the docs and then show up to competition and run a blue path on the red side of the field and have a bad time. But, I guess that most people making auto paths are probably aware of the path mirroring requirement (hopefully) and are either using their own solution or know about the PPLib option. I'll change the default to false.
