### ISSUE TITLE
Pathplanner Lib Vendor dep stops working

### ISSUE THREAD

**Issue by witherslayer67** [mjansen4857/pathplanner#234]
Every time I close then open 2023 WPILib VSCode, the pathplanner lib stops working and all pathplanner code is an error. Every time I have to Uninstall the vendor dep, and then reinstall it, then it works.

**Comment by mjansen4857** [comment]
This is probably an issue with vscode/wpilib. Are you using Java or C++? If it is showing errors, does it still build? If you're using c++, you may just need to run the "WPILib: Refresh C++ IntelliSense" command.

**Comment by witherslayer67** [comment]
It resolved itself after a little more use! thank you though!
