### ISSUE TITLE
Install Library Error:unable to get local issuer certificate

### ISSUE THREAD

**Issue by Macattack124** [mjansen4857/pathplanner#236]
I am trying to install the java library and I keep getting the error saying it is unable to get local issuer certificate.

**Comment by mjansen4857** [comment]
This is going to be an issue with your machine. There's not really anything I can do about it on my end that I know of. What OS are you using? Have you tried a different machine/internet connection? Something about your setup isn't happy with the SSL of the repo for some reason.

**Comment by Macattack124** [comment]
I am using Windows 10. Is there a way that this can be installed offline?

**Comment by mjansen4857** [comment]
Download the `PPLib-Maven` artifact from [here](https://github.com/mjansen4857/pathplanner/actions/runs/4018878916). You can go to newer workflow runs to download a new version whenever updates are made, but I just linked the latest.

Extract the zip and open the `maven` folder, then the `development` folder. There should be a `com` folder in here. Drag the `com` folder into `C:\Users\public\wpilib\2023\maven`

Then, download the vendordep json from [here](https://3015rangerrobotics.github.io/pathplannerlib/PathplannerLib.json) and place this file into `C:\Users\public\wpilib\2023\vendordeps`

Finally, install PPLib using the "install new libraries (offline)" option in vscode

**Comment by Macattack124** [comment]
So when I extract the PPLib-Maven, it comes up with a bunch of GROUP and M GROUP folders. When I go into each of them I unable to find the maven or development folder. 
![Uploading maven.PNG…]()

**Comment by mjansen4857** [comment]
Are you sure you downloaded the one that says "Maven" specifically? The other downloads on that page will be set up like you described, but the "Maven" one will be correct.
