### ISSUE TITLE
Robot drives full speed left (increasing Y) when selecting red alliance in driver station

### ISSUE THREAD

**Issue by apanteli23** [mjansen4857/pathplanner#250]
We are using the PPSwerveControllerCommand with automatic mirroring for swerve drive, everything works as expected when Team Station is set to a blue station but when we switch to the red station it drives full speed field relative left. We have our paths drawn on the blue side and have verified that the gyro is correctly set. Our full code is here: https://github.com/WHS-FRC-3467/Skip-5.13
The specific command we use is:
`public SequentialCommandGroup followTrajectoryCommand(PathPlannerTrajectory traj, boolean isFirstPath) {
        PIDController thetaController = new PIDController(1.2, 0, 0);
        PIDController xController = new PIDController(1.0, 0, 0);
        PIDController yController = new PIDController(1.0, 0, 0);
        thetaController.enableContinuousInput(-Math.PI, Math.PI);

        return new SequentialCommandGroup(
             new InstantCommand(() -> {
               // Reset odometry for the first path you run during auto
               if(isFirstPath){
                   resetOdometry(traj.getInitialHolonomicPose());
               }
             }),
             new PPSwerveControllerCommand(
                 traj, 
                 this::getPose, // Pose supplier
                 SwerveConstants.SWERVE_DRIVE_KINEMATICS, // SwerveDriveKinematics
                 xController, // X controller. Tune these values for your robot. Leaving them 0 will only use feedforwards.
                 yController, // Y controller (usually the same values as X controller)
                 thetaController, // Rotation controller. Tune these values for your robot. Leaving them 0 will only use feedforwards.
                 this::setModuleStates,  // Module states consumer
                 true, //Automatic mirroring
                 this // Requires this drive subsystem
             ) 
             .andThen(() -> stopDrive())
         );
     }`
 and 
```
public class TestAuto extends SequentialCommandGroup {
  /** Creates a new TestAuto. */
  public TestAuto(DriveSubsystem drive) {
    // Add your commands in the addCommands() call, e.g.
    // addCommands(new FooCommand(), new BarCommand());
    PathPlannerTrajectory backUp = PathPlanner.loadPath("BackUp", 1.0, 1.0);
    addCommands(
      drive.followTrajectoryCommand(backUp, true)
    );
  }
}
```
I am assuming it is our implementation of the mirroring is incorrect but we are following the wiki.

**Comment by mjansen4857** [comment]
You need to transform the initial state and reset your odometry based on that. The `getInitialHolonomicPose` method does not transform it

**Comment by We-Gold** [comment]
> You need to transform the initial state and reset your odometry based on that. The `getInitialHolonomicPose` method does not transform it

Is this required if we are using `autoBuilder.fullAuto()`?

**Comment by mjansen4857** [comment]
No. That will handle resetting odom for you.
