### ISSUE TITLE
End Point always locked

### ISSUE THREAD

**Issue by PatribotsProgramming** [mjansen4857/pathplanner#255]
The end point on any given path is always locked, regardless as to what option is selected. It can, however, still be modified by directly editing the X and Y values, it just cannot be dragged. I am unsure if this is the intended response, and if locked should also have a locked X and Y value for their position if editing directly; I believe that the locking is only there to prevent the mouse from accidently moving the point though, so this might be a simple fix.

**Comment by hadley31** [comment]
PR #254 to fix this
