### ISSUE TITLE
Using the path duplicate function does not copy non-pathpoint markers.

### ISSUE THREAD

**Issue by WAaron-500** [mjansen4857/pathplanner#267]
Path to be copied:

![image](https://user-images.githubusercontent.com/61605186/221699150-fb7ed820-f977-4de3-8c70-5951e4c710b2.png)

Path when copied:

![image](https://user-images.githubusercontent.com/61605186/221699246-e1e287f4-0ad3-4dd6-8246-38189695a36c.png)

**Comment by WAaron-500** [comment]
Also, cannot add new markers to a duplicated path as well.

**Comment by WAaron-500** [comment]
Forgot to add, when running the copied path, the markers also don't exist (commands attached to the markers don't run)

**Comment by mjansen4857** [comment]
Yeah noticed this a while back but its hard to get time to work on it. I believe it lets you add markers if you close and reopen the app.

**Comment by WAaron-500** [comment]
Yeah, that's what I was thinking do you know where all the GUI stuff is located, I can help fix it if I know which file to look at... not very good at programming, but Ill try my best
