### ISSUE TITLE
Stop point being skipped

### ISSUE THREAD

**Issue by jonahsnider** [mjansen4857/pathplanner#271]
Expected behavior:
https://user-images.githubusercontent.com/7608555/222873960-2f831025-7733-431c-b70f-f46853a8b830.mov
![preview of video](https://user-images.githubusercontent.com/7608555/222874403-7ba7f676-548c-4224-96d2-613be527b6c0.gif)

Actual behavior:
https://user-images.githubusercontent.com/7608555/222873965-4c4d237b-10f7-4014-b687-7e4f107b882c.mov
![preview of video](https://user-images.githubusercontent.com/7608555/222874382-019f2e2e-1d4a-4f7f-ab7e-9332f430ef08.gif)

Path:
[bug.path](https://github.com/mjansen4857/pathplanner/files/10887382/bug.path.txt)

Trajectory `.toString()`:
[trajectory.txt](https://github.com/mjansen4857/pathplanner/files/10887414/trajectory.txt)

The actual behavior is using simulated robot code, but we first noticed the issue on a real robot.
If you're unable to reproduce this bug locally, I can try creating a reproduction repo, as I am unable to share my team's full source code until after the season.

The simulation is super barebones, we just "teleport" the robot wherever Pathplanner is asking us to go:
![image](https://user-images.githubusercontent.com/7608555/222874061-eccd9996-3aa1-4f62-baaa-477ebfb261d3.png)

We load the path in a standard manner, and follow it using `SwerveAutoBuilder#followPath()`:
![path declaration](https://user-images.githubusercontent.com/7608555/222874095-8cb9d2ce-37aa-49f5-a3d4-0d0b42027d6a.png)
![autoBuilder declaration](https://user-images.githubusercontent.com/7608555/222874132-b77234d4-7850-4831-a7a1-bdf990c69e0a.png)
![auto command](https://user-images.githubusercontent.com/7608555/222874108-5aaaaec0-8980-4dbf-9630-d9c85b0b8c8f.png)

**Comment by mjansen4857** [comment]
Stop points are for path groups. Loading it as a single path will not split the path into a group.

**Comment by jonahsnider** [comment]
Good catch! Our path works as desired once we load & follow it as a group. Do you think there's anything that could be changed in PathPlannerLib to make it harder to make this kind of mistake? I feel like this is probably something that happens to lots of users.
