### ISSUE TITLE
[BUG] Field Relative X Coordinates are off by 1 foot

### ISSUE THREAD

**Issue by hamster1147** [mjansen4857/PathPlanner#28]
When using Field Relative coordinates for X, the generated points seems to always be offset positive 1 foot. Field Relative Y coordinates seem to be correct.

**Comment by mjansen4857** [comment]
This is due to the 2020 field being shorter than previous years. The solution I had for the GUI didn't work for the generation I guess. It should be fixed in ef8cd95.
