### ISSUE TITLE
Missing (new) C++ 2023.4.3 build in maven

### ISSUE THREAD

**Issue by rbiliff** [mjansen4857/pathplanner#284]
Since Pull #282 got merged, its probably a good idea to sync up C++'s 2023.4.3 to be (mostly) in-sync with Java's 2023.4.3 (or just make C++ have a 2023.4.4 version but that feels kinda bad)

**Comment by mjansen4857** [comment]
Will push a new release soon. Been super busy with 2 regionals back to back so haven't had the time. I'll probably just do a .4 for each since there is currently a PR for java as well.
