### ISSUE TITLE
PathPlanner Not Connecting to Server on MacOS

### ISSUE THREAD

**Issue by burakdemirelli** [mjansen4857/pathplanner#286]
Having tested on different Macbooks, all connected to the robot wirelessly, Pathplanner could not connect to the real-time diagnostics tool in the app. Trying it on a Windows machine resolved it for now. If there is more information needed, I can collect it and provide it.

**Comment by Ardusa** [comment]
Was this ever resolved?

**Comment by burakdemirelli** [comment]
> Sorry if I already asked this on CD but is this for the app store version or the version downloaded from github?

Sorry, I did not see this before. This was seen on the version downloaded from the app store.

**Comment by mjansen4857** [comment]
This should be fixed in the main branch already with the switch to using network tables so I will close this unless the issue pops back up again.
