### ISSUE TITLE
Duplicating paths deletes markers.

### ISSUE THREAD

**Issue by We-Gold** [mjansen4857/pathplanner#298]
On MacOS (I haven't tested on Windows), when I duplicate paths, the markers are deleted, except for stop points. I have been able to work around this by closing PathPlanner, duplicating the path file, and opening it again. I have also noticed that when I duplicate a path and add a marker (inside the app), I can't add markers until I close and open it again.

**Comment by mjansen4857** [comment]
Already fixed but unreleased
