### ISSUE TITLE
2020 Image Field Dimensions - Balls in Trench

### ISSUE THREAD

**Issue by DeanDavis** [mjansen4857/PathPlanner#30]
According to field drawings the center of the first Power Cell in the Red Trench is 27.75 inch from the inside wall. When I place my robot at 2.3125 feet on the Y-Position I would expect that the center of the robot would be aligned with the center of the PC on the field drawing but it isn't, it's off by a little.
Not a huge deal, can compensate for it.

I tested against other field elements and other things do align perfectly.
Example is the offset of the center of the upper goal is 7.88833333 feet from the inner wall. Placing a robot at that Y-Offset aligns it perfectly.
The Initiation line is set at 10 feet.

![Screen Shot 2020-02-24 at 9 20 53 AM](https://user-images.githubusercontent.com/12413449/75159869-00424a80-56e7-11ea-8eb0-d81df1366019.png)

**Comment by mjansen4857** [comment]
Thanks for letting me know. When I made the image I basically just traced over the power cells from a game manual field image so I was never sure if they were in the correct place.

I just updated the position of the power cells in both trenches in 5bac9a2 and they should now be at the correct X and Y position.
