### ISSUE TITLE
Path Optimization feature

### ISSUE THREAD

**Issue by srimanachanta** [mjansen4857/pathplanner#302]
PathPlanner's main advantage as a path generator is the high level of precision it offers in the creation and generation of paths. Lacking for PathPlanner, and many other major path generation tools, is the optimization aspect. Many other path generators have this but lack many of the other features that make PathPlanner popular. An idea is to add an optional path optimization mode. Just like how the holonomic mode can be toggled on, an optimization mode can be enabled where the user has to input all the relevant robot dimensions (Mass, MoI, Max Linear and Angular Velocity and Acceleration, Max Torque, Trackwidth / relevant kinematic constant) and PathPlanner uses these constants along with a Path/system optimizer such as [CasADi](https://web.casadi.org/) to optimize the created trajectories on a button press. 

Some issues with this would be the fact that many of the fine tune control users may enter may be overwritten so some middle ground will need to be established. CasADI has C++ and Python implements and I am not so sure about Dart's native layer abilities. 

I understand this would be a massive feature that may not be able to be implemented.

**Comment by mjansen4857** [comment]
Optimization is not something I think I can reasonably accomplish and maintain mostly by myself. I'd recommend Choreo for that. But, I am going to group this + a few other issues in #675 to try and accomplish a more accurate path generation while maintaining the ability to generate on-the-fly.
