### ISSUE TITLE
Switching to metric doesn't affect how the robot is displayed on the field.

### ISSUE THREAD

**Issue by haxoc** [mjansen4857/PathPlanner#32]
When in metric mode, the robot becomes a fraction of it's actual size and the speed when playing the path is greatly reduced because it is probably still displaying in feet.
![Screenshot from 2020-03-09 14-06-48](https://user-images.githubusercontent.com/46831897/76257614-ed348c00-6249-11ea-8ef2-1d1aae3cbe18.png)
![Screenshot from 2020-03-09 14-06-21](https://user-images.githubusercontent.com/46831897/76257618-eefe4f80-6249-11ea-9af8-18788d984992.png)

**Comment by minglethepringle** [comment]
+1. Same problem.

**Comment by mjansen4857** [comment]
Fixed in 9f04d2d

The units setting was not being read correctly so it always defaulted to feet.
