### ISSUE TITLE
Add ability to override target rotation in holonomic path following commands

### ISSUE THREAD

**Issue by mjansen4857** [mjansen4857/pathplanner#339]
This could be useful for taking over rotation near the end of a path to ensure the robot is aiming at a game piece, etc.

**Comment by WarrenReynolds** [comment]
Food for thought: If you are going to do this, you may as well add the ability to adjust x and y offsets as well as sometimes the robot might need to move sideways or closer as well to score or pickup.  

What every method you are going to use to bring the robot back to the correct holonomic rotation for that point in the path after handing control back to path planner, use the same method for X and Y offsets.   
Or you could just let the x, y and theta controllers handle "return to path planner control" corrections.  Another idea could be to make them profiled controllers so the "return to path planner control" is smooth.
Just some ideas.

**Comment by mjansen4857** [comment]
Its not really applicable to both rotation and translation the same way. Rotation is already handled by a profiled pid controller, so it is really simple to just feed the new target into that. But translation is not. Overriding the translation would really need to be done with a different trajectory. Just feeding new targets to the error controllers would still be fighting with the commanded velocities from the original trajectory. Its probably best if this is just left up to the user, either through creating a new trajectory or overriding the output chassis speeds entirely.
