### ISSUE TITLE
App breaks when opening a path which uses a deleted path

### ISSUE THREAD

**Issue by hadley31** [mjansen4857/pathplanner#349]
## Steps to reproduce:
1. Create a new path "New Path"
2. Create a new auto
3. Add follow path command and use "New Path"
4. Delete path "New Path"
5. Open auto

![image](https://github.com/mjansen4857/pathplanner/assets/37554439/bb75ec9f-874e-47e3-8d47-6fc9fed3a8c3)

## Proposed solution:
Check if path is used by any autos, and if so, prevent deletion

**Comment by mjansen4857** [comment]
Will need a bit more complex solution, as paths can be deleted manually from the file system. Follow path commands in autos can be empty, so it's likely better to empty out the commands with a missing path, then display some sort of warning icon over autos with missing paths in the project browser so you can tell something is wrong with it. The popup when deleting a path should also change to notify the user if the path is in use, and which autos are using it.
