### ISSUE TITLE
Try to run on Mac but crashes when opening

### ISSUE THREAD

**Issue by kinahawi** [mjansen4857/pathplanner#362]
When I try to run the program, it attempts to start, but then closes unexpectedly. No error  message is given. Tried uninstall and reinstall but no luck. MacBook Pro running Ventura 13.5.2

**Comment by jonahsnider** [comment]
Duplicate of #360?

**Comment by mjansen4857** [comment]
The main branch is not released. Do the terminal command in the last comment of #360

**Comment by kinahawi** [comment]
Thanks. I didn’t recognize that as a terminal command. That seems to have fixed it.
