### ISSUE TITLE
Command reordering bug when dragging commands around

### ISSUE THREAD

**Issue by hadley31** [mjansen4857/pathplanner#400]
When dragging commands to reorder them, the command trades places with the command after it. 

![f0a37cfe-6dfb-4784-88db-7ca3c8714b5d](https://github.com/mjansen4857/pathplanner/assets/37554439/0f095e75-0415-45d2-9d00-29487836d2f2)

**Comment by mjansen4857** [comment]
I swear I've fixed this same bug on like 3 separate occasions. I'll take another look then
