### ISSUE TITLE
Ability to pause/resume and seek through path/auto simulations

### ISSUE THREAD

**Issue by mjansen4857** [mjansen4857/pathplanner#415]
Suggested [here](https://www.chiefdelphi.com/t/pathplanner-2024-beta/442364/80#feedback-and-ideas-2)

**Comment by binex-dsk** [comment]
to add a little bit to the original suggestion: a trim feature of sorts to only watch a small portion of a path over and over.

**Comment by mjansen4857** [comment]
That greatly increases complexity, since a lot more custom work needs to be done. For now, it will just be a normal seek bar and you can replay sections by moving the seek bar manually.

I'll come back later to add that functionality.
