### ISSUE TITLE
Main Java Usage Wiki Page has not been updated for the latest Beta release

### ISSUE THREAD

**Issue by lohengrin332** [mjansen4857/pathplanner#417]
The [PathPlannerLib Java Usage page](https://github.com/mjansen4857/pathplanner/wiki/PathPlannerLib:-Java-Usage) still references the `PathPlanner` class, which does not seem to exist in the latest version of the 2024 beta. Please let me know if there is another page I should use as a starting point for learning the new library. Thanks.

JD Lewis
FRC 6377 - Howdy Bots

**Comment by mjansen4857** [comment]
2024 examples are in the sidebar. I also added their links to the main page.
