### ISSUE TITLE
2023 wiki link

### ISSUE THREAD

**Issue by bruingineer** [mjansen4857/pathplanner#419]
Is there a way to view the wiki in its 2023 form? I thought I remembered seeing a link somewhere, but I searched google and Chief Delphi and couldn’t find it.

**Comment by mjansen4857** [comment]
The usage example pages for 2023 PPLib are linked at the bottom of the wiki home page. If you need pages for the GUI, try the way back machine: https://web.archive.org/web/20230000000000*/github.com/mjansen4857/pathplanner/wiki
