### ISSUE TITLE
Unable to Set start point Holonomic Rotation when editing a path

### ISSUE THREAD

**Issue by WarrenReynolds** [mjansen4857/pathplanner#421]
Dev 403 release.
I might be missing something, but how do you set the Holonomic Rotation on the start point of a path.  Looking at last years game, we faced the alliance wall (180 degrees) and I can't for the life of me work out how to set that.  The rectangle that you usually rotate doesn't appear and if you select the start point with the mouse, only a circle around it appears with no handle to rotate it.

![image](https://github.com/mjansen4857/pathplanner/assets/86037820/6726cb96-eda7-4d64-b95e-91242265afc2)
Obviously not a real path, just playing with the editor.

OK, I just worked it out, you can't set the holonomic rotation when editing a path, you can only set it in an auto by optionally ticking the starting pose.  This sort of makes it hard to visualise and edit autos. To visualise the path with a starting pose, you need to be in the autos section, but to make changes to the path and events, you have to be in the paths section, but when you are in the paths section it assume a starting hlonomic rotation of 0 degrees in the visualisation.  Would it be possible to include the optional starting pose bit in the paths editor? ie Associate a starting pose with a path.

I can see the issue when chaining paths together, if one path finishes with a different holonomic rotation to the beginning holonomic rotation of the next path, but if this happens just ignore starting holonomic rotations for junctions in paths (like it is now).  

At the moment when finding and joining a path, I assume it is seeking to match the first rotation target it finds in the path.   You could leave this as is and only use the starting holonomic rotation of a path when it is used in an auto.

**Comment by mjansen4857** [comment]
You can't set one because the starting state of a path is not pre-defined anymore due to path replanning. The solution to this is to add an optional "preview starting state" that is similar to an auto's starting pose but for paths, and only affects the path preview.

Closing this as it has already been merged in #420
