### ISSUE TITLE
Program crashes when Next Control Length is set to 0.

### ISSUE THREAD

**Issue by RedThunder7166** [mjansen4857/pathplanner#424]
If you set the Next Control Length to 0 and hit enter, everything looks fine. Then, if you click on the box again and click off, the program crashes.
It also crashes if you try to change the value after it was set to 0.

Video demonstration:
https://github.com/mjansen4857/pathplanner/assets/44242651/cd539263-c3e9-4072-8862-54dacd5d689e

**Comment by mjansen4857** [comment]
The control length should never be set to 0, as that completely breaks the curve. The fix here is going to be to limit the minimum length that can be specified to something small like 0.1 or 0.05.
