### ISSUE TITLE
add linuxarm64 support

### ISSUE THREAD

**Issue by ryanshoff** [mjansen4857/pathplanner#428]
Would it be possible to add a linuxarm64 build target to the PathplannerLib-cpp CI? 

Ex:  https://3015rangerrobotics.github.io/pathplannerlib/repo/com/pathplanner/lib/PathplannerLib-cpp/2024.0.0-beta-3/PathplannerLib-cpp-2024.0.0-beta-3-linuxarm64static.zip  does not exist.

**Comment by mjansen4857** [comment]
Will be in next release
