### ISSUE TITLE
Add method to create a SendableChooser with all autos in deploy directory

### ISSUE THREAD

**Issue by mjansen4857** [mjansen4857/pathplanner#431]
Should take an optional path name for the default option, if no default is given, use `Commands.none()`

**Comment by WarrenReynolds** [comment]
We used the preferences table for list.  We had a list of Text Key pairs, with key names of Auto01, Auto02, Auto03, up to Auto20.

Then we would populate these keys with the filenames of path files we wanted to be listed in the auto chooser, through the RIO preferences table on our driver station dashboard.  This gave us the ability to pick and choose (and order) which files in the deploy folder we wanted on the dashboard auto chooser, as we found we had a lot of test paths and variations that we didn't particularly want in the auto chooser, but didn't want to delete them from the deploy folder either.

It also gave us the ability to add a new auto without needing to re-compile any code.  We would just deploy the path file to the deploy folder and modify the RIO preference table, with the new name of the path file.

In RobotInit, we would iterated through these keys, adding an entry to the auto chooser for every none empty auto key that it found.
