### ISSUE TITLE
no way to reverse waypoint?

### ISSUE THREAD

**Issue by DJ-Laser** [mjansen4857/pathplanner#437]
I was using the 2023 version and I made some paths for differential drive. A cool feature was the reverse checkbox, however when I ran the beta so I could try the auto maker it was seemingly gone. Am I just not seeing it or was this removed?

**Comment by mjansen4857** [comment]
If you're talking about reversing the path, you need to have holonomic mode off then the reverse checkbox will show up. If you're talking about the "reversal" point, this is now done through chaining multiple paths together in an auto.
