### ISSUE TITLE
Would like a command-line interface for path generation

### ISSUE THREAD

**Issue by username115** [mjansen4857/pathplanner#44]
Given saved path files from a previous usage of the Path Planner tool, I would like a way to generate output (csv or arrays) from a command line interface.

This would allow us to store the path files in our repository so they could be edited later, and generate the output as part of our build process. Doing so would prevent situations where a developer forgets to generate the output after editing the path. It would also follow the DRY (Don't Repeat Yourself) principle: https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Comment by mjansen4857** [comment]
The 2022 version of PathPlanner will move path generation over to a robot-side library so this will no longer be needed.
