### ISSUE TITLE
PathPlannerAuto not working at all 

### ISSUE THREAD

**Issue by 0gottogo0** [mjansen4857/pathplanner#451]
`Unhandled exception: java.lang.IncompatibleClassChangeError: class com.pathplanner.lib.commands.PathPlannerAuto has interface edu.wpi.first.wpilibj2.command.Command as super class
Error at java.base/java.lang.ClassLoader.defineClass1(Native Method): Unhandled exception: java.lang.IncompatibleClassChangeError: class com.pathplanner.lib.commands.PathPlannerAuto has interface edu.wpi.first.wpilibj2.command.Command as super class
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)`
this error appears in the riolog every time I try and run an auto. My code is on github at this link: https://github.com/0gottogo0/Swerve-drive-test

**Comment by mjansen4857** [comment]
You need to use the 2024 WPILib beta. PPLib 2024 is not compatible with WPILib 2023.

**Comment by 0gottogo0** [comment]
Oh
