### ISSUE TITLE
Swerve - rotate around a chosen Center of Rotation

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#47]
Like the option to determine an heading of Swerve robot during the path, it will be nice if you can choose to perform turn around a chosen Center of Rotation as part of the path.

e.g.:
As you can see in the video below, during the execution of the path, around the last bottle it seems that as part of the path, the robot rotates around that bottle (in this case the last bottle is the Center of Rotation).
https://www.youtube.com/watch?v=tlSXXfKMK6U

**Comment by mjansen4857** [comment]
Going to close this for now because I don't think it provides enough utility to warrant all the work that would need to be done to implement it. It makes sense for the at home challenges but I think its a bit too niche for normal FRC games.
