### ISSUE TITLE
Posibility to change pathfinding algorithm 

### ISSUE THREAD

**Issue by Ramtech59Sensei** [mjansen4857/pathplanner#470]
**Is your feature request related to a problem? Please describe.**
There is an option to change path finding algorithm from AD* to LocalADStarAK* adapted algorithm 
Can we change the path finding algorithm to any other path finding algorithm?

**Describe the solution you'd like**
Since the option to change already exist. Can we use this option "Pathfinding.setPathfinder(new LocalADStarAK());"
to change to another algorithm, if we implemented correctly to return same format of data ?
mainly I'm talking about  RRT* FN (static environment ) and RRT* FND (dynamic environment aka object avoidance )

**Additional context**
algorithm coded in this github
https://github.com/grzesiek2201/RRT-STAR-FND-Algorithm

**Comment by mjansen4857** [comment]
Create a class that implements the `Pathfinder` interface then you can pass an instance of that to the setPathfinder method.
