### ISSUE TITLE
wiki error or missing supplier 

### ISSUE THREAD

**Issue by Ramtech59Sensei** [mjansen4857/pathplanner#472]
**Describe the bug**
Java Example: Follow a Single Path 
In the construction of the "FollowPathHolonomic" 
the line below
`this::resetPose, // Method to reset odometry (will be called if your auto has a starting pose)`
the supplier is no define in the constructor signature in the code in Java, in c++ this supplier is not present in the example 
Is this resetPose not use or the robot is always reset to the first pose in the path ?

**Comment by mjansen4857** [comment]
Was an error with the wiki. Fixed
