### ISSUE TITLE
Paths and Autos are loading in deploy when first created

### ISSUE THREAD

**Issue by narmstro2020** [mjansen4857/pathplanner#486]
Reproducing this for me was straight forward.  The minute I create a path or an auto it should appear in deploy autos and paths accordingly.  This isn't always the case or sometimes I have to alter the default before it appears.

**Comment by mjansen4857** [comment]
This is intended. They won't be saved to disk until you make an edit to them because there is really no use case for the default path or auto. If you create one and don't make an edit, it won't be saved to disk to avoid clutter from an unused default path just sitting in your project.
