### ISSUE TITLE
Logging callback for path ending

### ISSUE THREAD

**Issue by Gold872** [mjansen4857/pathplanner#493]
There isn't an easy way of knowing when to clear the trajectory from a Field2d object without either adding something at the end of a command, which wouldn't work if the command is interrupted (if time runs out).

A good solution for this would be to have another callback method for whenever the auto command is done following a trajectory, which will get called at the end of the auto command, even if it is interrupted.

**Comment by mjansen4857** [comment]
I think a better solution here is just to call the active path callback with an empty list when the path following commands end. This avoids needing to add a separate callback.

**Comment by Gold872** [comment]
That's easy enough to do, if you want I could make a simple PR for it

**Comment by mjansen4857** [comment]
Up to you. I’ll probably be able to get to it tomorrow if not.
