### ISSUE TITLE
Unmodified new or example paths aren't saved to the deploy directory

### ISSUE THREAD

**Issue by UserC2** [mjansen4857/pathplanner#499]
**Describe the bug**
"Example Path" or new, unmodified paths (renaming the path still results in this bug) appear in PathPlanner, but disappear when PathPlanner is closed, as they aren't actually saved to disk. Using these paths crashes the robot code since they do not exist on disk.

**To Reproduce**
1. Open a project in PathPlanner without any paths in it
2. "Example Path" is created in the GUI
3. "Example Path" does not exist in the `deploy` directory, but is shown in PathPlanner
4. Create an auto using this path
5. Reopening PathPlanner causes the auto to display an error saying the path doesn't exist
6. The robot code will crash as it isn't able to find the path

Alternatively, with a new path:
1. Open a project in PathPlanner (can have paths already)
2. Create a new path (can rename it as well) but do not modify it
3. The new path does not exist in the `deploy` directory, but is shown in PathPlanner
4. See steps 4-6 above

**Expected behavior**
The path is saved to disk when created so that using the path, unmodified, does not crash the code. This isn't likely to cause issues when developing autos (you likely won't use the example path unchanged), but can lead to frustration during testing (e.g. setting up PathPlanner in simulation).

**Versions: (please complete the following information):**
 - OS: Windows 11
 - GUI Version: 2024.0.0-beta-5
 - PPLib Version: 2024.0.0-beta-5.1
 - PPLib Language: Java

**Comment by mjansen4857** [comment]
#486 

This is intended to prevent clutter from a bunch of default paths that were created then forgotten about
