### ISSUE TITLE
Named commands not working - PathPlanner 2024

### ISSUE THREAD

**Issue by rakrakon** [mjansen4857/pathplanner#504]
Named commands not published to pathplanner

Registered non null commands using methods in named commands class.  
Run simulation in order to publish the named commands.

Named commands should appear in pathplanner app.

![image](https://github.com/mjansen4857/pathplanner/assets/68773850/6c4ec968-e2d2-481e-be9b-e8726f621959)
![image](https://github.com/mjansen4857/pathplanner/assets/68773850/ff63a00f-29f6-44a0-b84d-9c567c7863dc)

 - OS: [e.g. Windows 11]
 - GUI Version: [e.g. 2024.1.1]
 - PPLib Version: [e.g. 2024.1.1]
 - PPLib Language: [e.g. Java]

**Comment by mjansen4857** [comment]
The GUI has no knowledge of your code. You have to type the name into the named command dropdown. Named commands are not synced between the GUI and code.

**Comment by TulikWIN** [comment]
yo how do i sync it tho ?
