### ISSUE TITLE
Import AutoBuilder Causes ValueError | Python 3.11

### ISSUE THREAD

**Issue by escime** [mjansen4857/pathplanner#517]
**Describe the bug**
When running any code with AutoBuilder imported, the following error is produced:
`ValueError: mutable default <class 'wpimath.geometry._geometry.Translation2d'> for field positionMeters is not allowed: use default_factory`

**To Reproduce**
Import AutoBuilder using the following code:
`from pathplannerlib.auto import AutoBuilder`

**Expected behavior**
Code should run with this import statement included as per [example code on this page.](https://github.com/mjansen4857/pathplanner/wiki/Python-Example:-Build-an-Auto)

**Screenshots**
Here's the full stacktrace I'm getting with the error.
![image](https://github.com/mjansen4857/pathplanner/assets/44032434/dad92bef-ba75-4ae2-9df5-623ed58e860e)

**Versions: (please complete the following information):**
 - OS: Windows 11
 - GUI Version: Not Applicable
 - PPLib Version: 2024.0.0b6.post1
 - PPLib Language: Python 3.11

**Additional context**
Sorry if this is something I'm doing wrong, but I'm not exactly a practiced Python developer and as far as I can tell from the error it's nothing my code is doing.

**Comment by mjansen4857** [comment]
This seems to be a problem with python 3.11+. I've been doing dev and testing with 3.10 and that works fine. I'll update the project to be compatible with 3.11

**Comment by mjansen4857** [comment]
Was a pretty minor fix. I'll push 2024.0.0b6.post2 when #518 gets merged which should fix this for you
