### ISSUE TITLE
OTF Pathfinding is deviating into a constrained zone

### ISSUE THREAD

**Issue by Gold872** [mjansen4857/pathplanner#519]
I have a simple program that starts in the center of the community (in front of the charge station), and it pathfinds to a small trajectory that leads the robot right up to the double substation. However, for some odd reason it is going into the other alliance's loading zone.

Here is a gif of what is happening
![ic8tR3XUll](https://github.com/mjansen4857/pathplanner/assets/91761103/c5f875c8-9e9a-4fbe-92d3-5e3c6652a7eb)

This is how my navgrid is set up
![image](https://github.com/mjansen4857/pathplanner/assets/91761103/b7cf1c02-7dfc-4a1f-ae42-2978efe95d77)

This is using the latest version of WPILib 2024 beta (beta-4), and the pathplanner version that came along with beta 4.

As for the path following configuration, I am using the default replanning behavior, and with a relatively low max velocity and acceleration, being 4.0 m/s and 2.5 m/s^2

**Comment by mjansen4857** [comment]
Are you setting dynamic obstacles in your code?

**Comment by Gold872** [comment]
Yes, but they aren't anywhere near the path (it's an uninitialized field object)

**Comment by mjansen4857** [comment]
It will still cause the path to be recalculated anytime dynamic obstacles are set. If you comment out wherever you are setting them it should prevent this. There is currently an issue where the robot will replan after a new pathfinding path comes in when doing curves like this.

Dynamic obstacles still has quite a few issues so its still not something officially supported. I will try to look into issues like this if they are an easy fix, but if its pretty difficult to find it will be much lower priority than everything else in the library. Although, at this point, I will probably just change dynamic obstacles to only cause a recalculation if a new obstacle would block the current path. This would mean it won't react to a better path opening back up, but should solve a lot of these random issues.

**Comment by mjansen4857** [comment]
Give pplib beta 6.1 a try and see if it helps at all. I also noticed in my testing it seems to happen most while rotating. You might want to increase your rotation delay distance to do the rotation over a straight path.

**Comment by mjansen4857** [comment]
Going to close this with #529 since that will change dynamic obstacles to only trigger the path to be recalculated if the obstacles interfere with the current path, and the requirements to trigger replanning were relaxed a bit in a previous PR.
