### ISSUE TITLE
Add Delay option after reaching a waypoint

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#53]
Would be cool, if you can add a delay after reaching a waypoint. 
e.g. in the example of rival trench auto you posted on CD, you can stay for 0.5 sec after you reached the balls, than continue the path.

**Comment by rjbell4** [comment]
FWIW, we do this as two paths in a `SequentialCommandGroup`, with a `WaitCommand` in between.

**Comment by mjansen4857** [comment]
I think it is better to do this with #73. This way you can just add a delay between paths instead of hard coding it in the path.
