### ISSUE TITLE
Paths names

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#55]
I noticed that if you press "Shift" when editing path name, is treat as you would press "CapsLock".

**Comment by mjansen4857** [comment]
I'm unable to reproduce this. Could you go more into depth on steps to reproduce or provide a screen recording of it happening or something? Have you ruled out the possibility of it being a hardware issue with your keyboard?

**Comment by lidor51** [comment]
Pressed shift to insert a capital letter, and after release, the following letter were upper case as well. The only way I can handle it, was go to another program, change to low case again, then go to PathPlanner.

**Comment by mjansen4857** [comment]
I can't reproduce this no matter what I do. If it is a bug it's likely a flutter bug which I can't really do anything about. I've upgraded the flutter version recently so I guess just wait and see if it's fixed whenever a new PathPlanner update comes out.

**Comment by mjansen4857** [comment]
Is this still an issue?
