### ISSUE TITLE
Link for C++ API documentation not working

### ISSUE THREAD

**Issue by rtsledge** [mjansen4857/pathplanner#555]
Link for the C++ API documentation doesn't appear to be working

**To Reproduce**
Click any of the C++ API documentation Links
or try to go here
https://pathplanner.dev/api/cpp/

**Comment by mjansen4857** [comment]
It's working fine. If you're on a school network it's likely being blocked.

**Comment by rtsledge** [comment]
hmm.. not on a school network.  I am using Chrome browser...  When I click "PPLib C++ API" from the "Getting Started" page 

![Capture1](https://github.com/mjansen4857/pathplanner/assets/156355055/dc71b8dd-cca0-41ac-8464-e164984df681)

It takes me to "https://pathplanner.dev/api/cpp/"

but that looks like 

![Capture2](https://github.com/mjansen4857/pathplanner/assets/156355055/a0121c60-2ed3-4dc5-8056-9c2c0bdf6a85)

**Comment by rtsledge** [comment]
oh wait never mind... I am sorry....
