### ISSUE TITLE
Local Host bug

### ISSUE THREAD

**Issue by oguiizim** [mjansen4857/pathplanner#561]
I was configuring my Path Planner 2024, and I saw that my host location was wrong, so I went to change it, but I clicked on a wrong number, and I pressed enter because I didn't notice, but now my pathplanner 2024 doesn't want to start anymore, I've uninstalled and reinstalled it, I tried to restore the data through Windows 11 settings, I wanted to know if you could help me resolve this.

**Versions: (please complete the following information):**
 - OS: [e.g. Windows 11]
 - GUI Version: [e.g. 2024.1.1]
 - PPLib Version: [e.g. 2024.1.1]
 - PPLib Language: [e.g. Java]

**Comment by mjansen4857** [comment]
If on windows, delete `shared_preferences.json` in `%AppData%/com.mjansen4857/pathplanner`

If on Mac, run `defaults delete com.mjansen4857.pathplanner` in terminal
