### ISSUE TITLE
Velocity Override doesn't work

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#57]
In both Holonomic & Differential Drive, the Velocity Override I wrote in a Waypoint doesn't get saved.

Besides that, for some reason there's no support for adding starting velocity.

**Comment by mjansen4857** [comment]
Fixed the velocity override issue in c7db3b9, however this will also require a PathPlannerLib change before it works on robot. I can't reproduce the not saving issue. Are you hitting the enter key after entering a value?

**Comment by lidor51** [comment]
Yes, I pressed enter for sure.

**Comment by mjansen4857** [comment]
I fixed an issue with the velocity override text boxes not showing the correct value. Maybe that is the issue you are talking about?

**Comment by amquake** [comment]
When setting the velocity override on the last waypoint, it doesn't seem to have an effect. Whatever value is specified is just ignored.
https://user-images.githubusercontent.com/7953350/150341161-9978cf31-8678-4660-a156-c0afc6090087.mp4
I figured out you could empty the text box and press enter to reset it to the null, which returned it to the default behavior.
https://user-images.githubusercontent.com/7953350/150341169-c90bd486-a42f-468e-af06-3e4485a89f07.mp4

**Comment by mjansen4857** [comment]
This is technically functioning as expected. A velocity override of 0 is not allowed since it would create an infinite loop in the generation code. I will change it to treat a 0 as a null value to prevent this from happening though.

**Comment by mjansen4857** [comment]
Fixed in [9a41c25](https://github.com/mjansen4857/pathplanner/commit/9a41c252007ee6cfcf8be0cb3fd7c1baff76208f)

I believe the issues with the velocity override box have been fixed now. If there's still issues after next release then reopen this.
