### ISSUE TITLE
Alliance field flip

### ISSUE THREAD

**Issue by 0x5b62656e5d** [mjansen4857/pathplanner#573]
**Describe the bug**
In the default autobuilder code for holonomic drives, there's a section where if the alliance is red, then the path should be flipped. However, when we were running the path, the return statements seem to be "flipped."
This is the path:

![image](https://github.com/mjansen4857/pathplanner/assets/112295217/017c4cfa-b882-4397-9f2a-9bcb7a002b60)

If we use the original code to check alliance, and set our alliance to RED in driverstation, the path should be flipped. However, the robot seems to be trying to get from the blue alliance side to the red alliance side. (The robot moves in a diagonal line towards the desired endpoint in the red alliance side)

**To Reproduce**
Create a similar path to the screenshot above
Run the path with the robot on the red alliance side + driverstation alliance set to RED 1

**Expected behavior**
Robot should move 3 meters horizontally (positive Y)

**Versions: (please complete the following information):**
 - OS: Win 11, MacOS Sonoma
 - GUI Version:2024.1.1
 - PPLib Version: 2024.1.2
 - PPLib Language: Java

**Additional context**
Original alliance check code:
```java
var alliance = DriverStation.getAlliance();
if (alliance.isPresent()) {
        return alliance.get() == DriverStation.Alliance.Red;
}
return false;
```

Changed code that currently works:
```java
var alliance = DriverStation.getAlliance();
if (alliance.isPresent()) {
        return alliance.get() != DriverStation.Alliance.Red;
}
return true;
```

**Comment by mjansen4857** [comment]
The flipping and the example code is working as intended. You need to have your odometry in the correct spot before running the path, either through having it reset via `PathPlannerAuto`, resetting it manually (you shouldn't do this except at the beginning of auto), or by already being near the start location.
