### ISSUE TITLE
Flip path override 

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#577]
Being able to override and specify our own flip alliance method.

E.g., if we don't want to follow PP new convention to stick oeigin on blue side, and want to implement a flip method in which origin is always on our alliance color side.

**Comment by mjansen4857** [comment]
I'm going to leave anything beyond the standard flipping up to the user to implement themselves before passing the paths to path following commands. PPLib is just built to work specifically for a blue alliance origin at a lot of different levels, I don't want to officially support doing something that could break it.

I really suggest just moving to using a blue alliance origin. It has been so much nicer to work with compared to having the origin change with the alliance.
