### ISSUE TITLE
Not able to spin the start pose rotation

### ISSUE THREAD

**Issue by FRC9427** [mjansen4857/pathplanner#583]
## Not able to spin the start pose rotation

When using a path planner, we are unable to change the start pose rotation

**Comment by mjansen4857** [comment]
You already opened #576 for this. It definitely is working. If you provide more info I can try to help.

**Comment by FRC9427** [comment]
We apologize for not noticing the issue with #576. Our problem has been resolved.Thank you for your help!!

**Comment by FRC9427** [comment]
We apologize for not noticing the issue with https://github.com/mjansen4857/pathplanner/issues/576. Our problem has been resolved.Thank you for your help!!

**Comment by mjansen4857** [comment]
No problem. Did you mean to reopen this?
