### ISSUE TITLE
Auto builder does not indicate the true source of an error thrown from WPILIB

### ISSUE THREAD

**Issue by bovlb** [mjansen4857/pathplanner#601]
https://github.com/mjansen4857/pathplanner/blob/aa883be5d64dcb2e5b46c29f9f9208df133982e6/pathplannerlib/src/main/java/com/pathplanner/lib/auto/CommandUtil.java#L89

https://www.chiefdelphi.com/t/pathplanner-parallel-command-group-error/453766?u=bovlb

I believe that this line correctly throws an exception if the commands being added to the ParallelCommandGroup have conflicting requirements.  I believe it could be more helpful in identifying where the problem is.

The try block at https://github.com/mjansen4857/pathplanner/blob/aa883be5d64dcb2e5b46c29f9f9208df133982e6/pathplannerlib/src/main/java/com/pathplanner/lib/auto/AutoBuilder.java#L736 could usefully add the filename to the message.  Perhaps something like:
```
throw new RuntimeException(String.format("Problem building auto %s", autoName), e);
```

**Comment by mjansen4857** [comment]
Fixed in 88ee403

Making release now
