### ISSUE TITLE
Typo in Java lib: PathPlannerAuto.getStaringPoseFromAutoFile

### ISSUE THREAD

**Issue by beamer159** [mjansen4857/pathplanner#605]
https://github.com/mjansen4857/pathplanner/blob/3a7fc679bb48563145dbafd41fdde12fb29bb931/pathplannerlib/src/main/java/com/pathplanner/lib/commands/PathPlannerAuto.java#L54

Should be renamed to `getStartingPoseFromAutoFile`

**Comment by mjansen4857** [comment]
No longer relevant as of #714
