### ISSUE TITLE
Allow for preset Auto starting pose to reference linked waypoints

### ISSUE THREAD

**Issue by ohowe1** [mjansen4857/pathplanner#616]
This is helpful when you don't want to have to update both the starting position in the first path of an auto and the preset auto position in the auto.

**Comment by mjansen4857** [comment]
I think a cleaner solution here may just be to have an option to force the preset starting pose to the first point of the first path, similarly to how it works for Choreo autos.

**Comment by ohowe1** [comment]
That sounds much better. Thank you
