### ISSUE TITLE
Path Planner Rotation Error

### ISSUE THREAD

**Issue by NuttyNitty** [mjansen4857/pathplanner#622]
**Describe the bug**
When creating the path, the holonomic rotation is not reached until the very end despite "Rotate As Fast As Possible" being turned on. We have tried setting rotation targets and changing angular velocity constraints, but they did not solve the issue.

**To Reproduce**
1. Copy the shown path (shown in screenshots).
2. Add rotation target at 0.5
3. Select "Rotate As Fast As Possible"
4. Run through path to see rotation targets not met until at the end of the path.

**Expected behavior**
We expected the rotation target to be met at 0.5, as well as we expected the full rotation as fast as possible instead of 

**Screenshots**
![Screenshot 2024-03-02 163655](https://github.com/mjansen4857/pathplanner/assets/123262135/8cab19d5-fba6-4210-81ab-9656aafb334b)
![Screenshot 2024-03-02 164257](https://github.com/mjansen4857/pathplanner/assets/123262135/ac809bb2-d531-4ccf-9086-71dc3ebf5d02)

**Versions: (please complete the following information):**
 - OS:  Windows 11
 - GUI Version: 2024.1.4
 - PPLib Version:  2024.1.4
 - PPLib Language:  Java

**Comment by mjansen4857** [comment]
This is working as expected. Translation is favored over rotation, so if you are moving at the max speed of the modules, there will not be any module speed left over to perform rotation. You need to make sure that your max module speed setting is correct, and adjust your max velocity constraint to leave room for rotation. This is probably best done with a constraint zone over the part of the path where you want to complete the rotation.
