### ISSUE TITLE
C++ Desktop Build Linking Fails

### ISSUE THREAD

**Issue by MrRedness** [mjansen4857/pathplanner#630]
**Describe the bug**
When building a 2024 wpilib C++ codebase that has pathplannerlib 2024.2.5 installed, if desktop/simulation support is enabled, linking fails. (worked fine on 2024.2.3).

**To Reproduce**
1. Install pathplannerlib 2024.2.5 as vendor library
2. Enable desktop support
3. Build or run simulation

**Expected behavior**
No error?

**Screenshots**
![image](https://github.com/mjansen4857/pathplanner/assets/16584585/1920de86-dadd-4ff1-a451-258aa6202217)

**Versions: (please complete the following information):**
 - OS: Windows 10
 - GUI Version: N/A
 - PPLib Version: 2024.2.5
 - PPLib Language: C++

**Comment by MrRedness** [comment]
Downloading and copying pathplannerlib into the project seems to work without issue. Unsure if this means the solution is related to using it as a vendor library or it was fixed in an update that hasn't been uploaded yet.

**Comment by mjansen4857** [comment]
Is your WPILib version updated? It is built against the latest wpilib

**Comment by BarrelDev** [comment]
Have you tried updating your Visual Studio Build Tools? Our team was facing the same issue but that resolved it.
