### ISSUE TITLE
Swerve Modules (Turning Motors) Spinning Randomly at End of Path

### ISSUE THREAD

**Issue by mikesmyths** [mjansen4857/pathplanner#633]
**Describe the bug**
When the end of path is reached, and we are executing a Named Command, Wait Command, or another path, the Swerve Modules are rotating at a random rate. The turning motors are spinning with zero velocity on the drive motors. The waypoints between paths are linked together. Autobuilder being used to create the auto command.

**Expected behavior**
Expect that when the path ends, no wheel movement would occur before the next path begins or when running a named command or wait command with no motion. 

**Screenshots**
Attached Pathplanner Screenshot:
![Screenshot 2024-03-10 190344](https://github.com/mjansen4857/pathplanner/assets/100612592/3d6f9df8-a7b6-4018-8f15-5a00187ee801)
YouTube Video of Issue:
https://youtube.com/shorts/DzKFGiGQfsg?si=D4CHxTG0RgtTOQcJ

**Versions: (please complete the following information):**
 - OS: Windows 11
 - GUI Version: [2024.1.4]
 - PPLib Version: [2024.2.5]
 - PPLib Language: [Java]

**Additional context**
Other Teams locally also experiencing the same issue. Unable to upload the paths and auto files to this portal but can send with instructions.

**Comment by mjansen4857** [comment]
This is going to be an issue in your swerve code, PPLib does not directly control your modules. If you're using a swerve framework, it would be best to get support from whoever created it.

If you're doing custom swerve code, I can't help too much, but my guess without too much info would be that you are not outputting zero velocity to the drive when the path following ends, so the last command sent to the motors is continuing to run. If you're going to do anything between paths, you should keep controlling the drivetrain the whole time. PPLib can't control it when not running a path following command.
