### ISSUE TITLE
AutoBuilder.conifgureCustom doesn't support flipping

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#634]
It's not possible to flip path with configureCustom, since it doesn't get BooleanSupplier of shouldFlip, insteaf it's set it to false.

The desired solution is to add it as a pram to the method, like all other config methods.

**Comment by mjansen4857** [comment]
The flipping happens within the command itself, on initialize. It is not possible to do this in AutoBuilder, since it can be used to build commands when code first starts, and the robot does not yet know which alliance it is on.

**Comment by mjansen4857** [comment]
Oh, for odom reset? Yeah, you're right. Can fix that.
