### ISSUE TITLE
Scrollable path & auto lists

### ISSUE THREAD

**Issue by jonahsnider** [mjansen4857/pathplanner#638]
**Is your feature request related to a problem? Please describe.**

We have A Lot of paths & autos in our PathPlanner project this year. So many that on some screen sizes, the list of paths/autos renders off the screen, making them inaccessible for editing.

**Describe the solution you'd like**

The sections in the project browser for paths & autos should be scrollable, so that all the items can be viewed.

**Additional context**
N/A

**Comment by mjansen4857** [comment]
Could you send some screenshots of what it looks like? The lists are scrollable so I’m not sure why it’s not working for you.

**Comment by jonahsnider** [comment]
Seems like the paths/autos themselves are scrollable, but folders are not:

![video](https://github.com/mjansen4857/pathplanner/assets/7608555/db513523-e012-4df7-87f9-634ec8724dbd)

**Comment by mjansen4857** [comment]
Yeah I don't think folders are included in the part that's scrollable. Should hopefully be an easy fix
