### ISSUE TITLE
PathPlanner crashing on MacOS when attempting to change path in an auto

### ISSUE THREAD

**Issue by jasonli0616** [mjansen4857/pathplanner#654]
**Describe the bug**
Using the PathPlanner GUI, the program crashes when clicking the dropdown (to change path) on a pre-existing follow path command, in an autonomous routine.

**To Reproduce**
1. Go to an auto created in the PathPlanner GUI
2. Add a Follow Path command, and select a path (or use a pre-existing one)
3. Click on the dropdown or on the text/path name, attempting to change the path
4. Program crashes at this point

**Expected behavior**
Dropdown appears with paths.

**Screenshots**
Screen recording using the [release downloaded from GitHub](https://github.com/mjansen4857/pathplanner/releases/tag/v2024.1.5):

https://github.com/mjansen4857/pathplanner/assets/75756042/02ee388f-4310-4e71-a0b6-115233dae5fa

Screen recording running from source in Flutter debug mode (with possibly relevant error message):

https://github.com/mjansen4857/pathplanner/assets/75756042/6ea0b6d1-8922-42c3-bc11-3ed8bb921efa

**Versions: (please complete the following information):**
 - OS: MacOS 14.3.1
 - GUI Version: 2024.1.5
 - PPLib Version: 2024.2.7
 - PPLib Language: Java

I have not tested this on Windows, or another Mac computer, but it is happening across projects.

**Comment by mjansen4857** [comment]
This appears to be a bug in the latest stable flutter version, caused by the paths list being long enough to be scrollable. I'll either replace the latest PP build with one made from a downgraded flutter version or the beta channel, depending on which one works.
