### ISSUE TITLE
Making Changes to paths causes other paths to not work

### ISSUE THREAD

**Issue by MrCollen** [mjansen4857/pathplanner#657]
We have paths and autos that are working great!   We begin working on another set of paths and an Auto which is a lot of saves and pushing the paths up to the robot to test.   At some point this messes up our other autos that were working that we have not touched.   Example, We have a simple auto that just drives straight for 5 meters.  We use this to test our gear ratios and odometry.  This test path works fine.  After making changes to other paths and autos something happens where none of our paths will work.  If I try to run the 5 meter auto again it acts unpredictable.  It will turn to the right and go for more than 5 meters and I have to kill it.

We have to back out path changes to get others to work again.  It seems to be after a lot of changes are made to other paths.  We have tried to reimage the Rio and that doesn't fix it.  So far the only fix we have to back out the changes we just did and the other paths work again. 

We are coding in java

**Comment by mjansen4857** [comment]
Can't reproduce + enough has changed that this report probably isn't valid anymore anyways
