### ISSUE TITLE
Scrolling doesn't work for autos list

### ISSUE THREAD

**Issue by 5690Programmers** [mjansen4857/pathplanner#660]
**Describe the bug**
Scrolling in the paths pane works as expected however in the autos pane it does not scroll

**To Reproduce**
1. Open pathplanner with many autos
2. Try to scroll
3. It doesn't scroll

**Expected behavior**
Being able to scroll to view all of my autos

**Screenshots**

**Versions: (please complete the following information):**
 - OS: Windows 11
 - GUI Version: 2024.1.6
 - PPLib Version: n/a
 - PPLib Language: n/a

**Additional context**

**Comment by rjbell4** [comment]
I am also seeing this.  I noticed it's scrollable for a second, and if I can manage to get the scroll bar to appear, I can scroll by dragging the bar, but generally, it's not scrollable.

I rolled back to 2024.1.4, and did not have this problem

**Comment by mjansen4857** [comment]
I'm not able to reproduce. So, I will need some more info about your exact setup + screenshots or videos if you can.

**Comment by UserC2** [comment]
> I'm not able to reproduce. So, I will need some more info about your exact setup + screenshots or videos if you can.

I have the same issue as well, I am running PathPlanner on Windows 11 (version 2024.1.6).

**Comment by Gavin32323** [comment]
> I'm not able to reproduce. So, I will need some more info about your exact setup + screenshots or videos if you can.

Hello, I am having this issue on MacOS as well. Here is a video. There are more autos on the right but I cannot scroll to them. I can work around this by changing the view of the list of autos, but that is annoying. Also I have had this issue on both v2024.1.2 and v2024.1.5. [https://youtu.be/qaXpJkYPeD8](url)

**Comment by rjbell4** [comment]
@mjansen4857 At your request, here's a GIF of v1.4 working
![PP-1 4](https://github.com/mjansen4857/pathplanner/assets/375968/65886e9a-374d-4f4d-b3a5-de6957efd339)

Here's a GIF of v1.5 not allowing me to scroll via my trackpad, nor bringing up the scrollbar on the right
![PP-1 5](https://github.com/mjansen4857/pathplanner/assets/375968/59680fd3-d4ac-42ae-bdcc-86dc80f616c2)

The setup is simply a standard Windows 11 laptop running the loadable 1.4 and 1.5 versions of PathPlanner.

**Comment by Gavin32323** [comment]
> @mjansen4857 At your request, here's a GIF of v1.4 working
> 
> ![PP-1 4](https://github.com/mjansen4857/pathplanner/assets/375968/65886e9a-374d-4f4d-b3a5-de6957efd339)
> 
> 
> 
> Here's a GIF of v1.5 not allowing me to scroll via my trackpad, nor bringing up the scrollbar on the right
> 
> ![PP-1 5](https://github.com/mjansen4857/pathplanner/assets/375968/59680fd3-d4ac-42ae-bdcc-86dc80f616c2)
> 
> 
> 
> The setup is simply a standard Windows 11 laptop running the loadable 1.4 and 1.5 versions of PathPlanner.
> 
> 

I was using a trackpad as well. If that is useful information.

**Comment by mjansen4857** [comment]
I still can't reproduce, but I think I found a difference that could cause issues on some trackpads for some reason. If you get a chance, can you try a build from [here](https://github.com/mjansen4857/pathplanner/actions/runs/8461998850?pr=669) and see if that solves the issue?

**Comment by Gavin32323** [comment]
Yes, this fixed the issue on my macbook. Can't test on my Windows 10 laptop until tommorow but I can assure it fixed it for MacOS. Thank you!

**Comment by mjansen4857** [comment]
Ok, I'm gonna assume that is the fix then. Thanks

**Comment by rjbell4** [comment]
I can also verify that the problem is fixed for me as well in the dev build
