### ISSUE TITLE
"Decorate" the robot rectangle

### ISSUE THREAD

**Issue by pordonj** [mjansen4857/pathplanner#667]
**Is your feature request related to a problem? Please describe.**
When drawing paths I'd like to visualize different simple things about my robot (intake region, shot path). I can imagine/eyeball/straight-edge these, but decorating my robot rectangle would offload a lot of this effort.

**Describe the solution you'd like**
Some way in the overall config to apply decorations to the robot rectangle on a given side (for simplicity, I think these could be rectangles centered with a given width/depth from the center of one of the robot sides).

**Additional context**
(Bad) Artist rendition of my idea here (colors/thicknesses not to scale)
![image](https://github.com/mjansen4857/pathplanner/assets/282467/94753308-6f8d-4568-9af3-5c2f41c52376)

I am totally down to do the work for this in a PR, but I poked around for a short time and couldn't figure out where/how the robot rectangle gets drawn

**Comment by ModBoyex** [comment]
Personally I would do some of this using mechanisms in the glass simulations. I could see this getting kinda messy.

**Comment by mjansen4857** [comment]
Depends on #902 as this can be an addition to that configurator
