### ISSUE TITLE
Goal Endstate Velocity Doesn't Work

### ISSUE THREAD

**Issue by anAvgCoder** [mjansen4857/pathplanner#668]
Thank you MJansen for this awesome app and library.

**Describe the bug**
The goal endstate velocity of a path doesn't work and the robot just stops at the end of the initial path

**To Reproduce**
![image](https://github.com/mjansen4857/pathplanner/assets/119552076/0df5cbbc-b06c-469a-9f73-8162832b527a)

1. Create 2 paths (New new path and new path in the screenshot)
2. New path begins exactly at the end of the new new path
3. Set a goal endstate value for new new path (any value doesn't work)
4. The robot will stop at the end of the first path and the velocity override doesn't work

**Expected behavior**
I expected that the robot would continue onto the second path with its velocity maintained

**Versions: (please complete the following information):**
 - OS: Windows 10
 - GUI Version: 2024.1.4 (tested with 1.5 as well)
 - PPLib Version: 2024.2.7 (tested with older versions as well)
 - PPLib Language: Java

**Comment by mjansen4857** [comment]
Unable to reproduce. Would need more info like your exact path/auto files.
