### ISSUE TITLE
Create way for robot to rotate in place

### ISSUE THREAD

**Issue by ModBoyex** [mjansen4857/pathplanner#671]
**Is your feature request related to a problem? Please describe.**
There are many situations in witch I find myself wanting to make paths that should rotate in place at some points. At the moment Path planner makes this really difficult because paths don't wait for the robot to finish getting to its end rotation before moving on to the next motion. 

**Describe the solution you'd like**
I would love to either see path planner wait for the rotation of the robot to be were it should be before moving on, or some other way of making an in place ration action.

**Comment by Derp88** [comment]
Cold you use extra waypoints + rotation targets?

https://pathplanner.dev/gui-editing-paths-and-autos.html#rotation-targets
