### ISSUE TITLE
Add trigger based option for event markers

### ISSUE THREAD

**Issue by mjansen4857** [mjansen4857/pathplanner#676]
Add the option for event markers to be used as a `Trigger` from within robot code, instead of supplying a command that will be run within the pathfinding command. With the current state of the commands framework, this won't be able to work in all situations unless you proxy everything in the auto command, but would still be a nice option to have for a lot of teams.

**Comment by lidor51** [comment]
@mjansen4857 can your further elaborate on the use-case? Not sure that the first sentence's in-depth meaning was clear enough for me.
