### ISSUE TITLE
NamedCommands::registerCommand will crash depending on static initialization order

### ISSUE THREAD

**Issue by r4stered** [mjansen4857/pathplanner#682]
**Describe the bug**
When calling NamedCommands::registerCommand(), the static vector namedCommands might not be initialized based on the order of compilation.

https://en.cppreference.com/w/cpp/language/siof

**To Reproduce**
1. Create a named command in C++ and call registerCommand on it. 
2. Hope the compiler initializes it incorrectly :)

**Expected behavior**
The vector should be initialized properly on the first call

Relevant FRC discord messages: 

https://discord.com/channels/176186766946992128/528555967827148801/1230553097307295805

**Comment by mjansen4857** [comment]
Fixed in #685
