### ISSUE TITLE
Replanning with trigger skipped markers

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#696]
Currently replanning isn't useful for us, since it might skip event markers.

E.g., A robot run to the center line, then come back to shoot. During the first path it uses a vision algorithm and managed to get a note 1m closer, meaning that in the way back it'll start from there. In the way back there's a marker that turns on the shooter, but it'll be skipped and the robot won't shoot.

The suggested behavior is adding an option to ReplanningConfig to trigger all skipped event markers (in order).

**Comment by mjansen4857** [comment]
No longer relevant as replanning was almost entirely removed in favor of leaving complex on-they-fly generation like that up to the user. A generalized PPLib solution caused a lot of hard to debug issues and doesn't work ideally for everyone.
