### ISSUE TITLE
Replanning without skipping a rotation target 

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#697]
Replanning might skip rotation targets and cause to undesired behavior of robot on the field.

The suggested behavior is if skipping a rotation target, set the new path to begin with "fast as possible" rotation target to the interpolated rotation target based on current robot location (interpolation between prev and next rotation targets).

**Comment by mjansen4857** [comment]
No longer relevant as replanning was almost entirely removed in favor of leaving complex on-they-fly generation like that up to the user. A generalized PPLib solution caused a lot of hard to debug issues and doesn't work ideally for everyone.
