### ISSUE TITLE
headingAngularVelocityRps Javadoc Suggestion

### ISSUE THREAD

**Issue by Hirose-Yuto** [mjansen4857/pathplanner#704]
This is a small mistake, but I noticed it while looking at the javadoc.
https://github.com/mjansen4857/pathplanner/blob/main/pathplannerlib/src/main/java/com/pathplanner/lib/path/PathPlannerTrajectory.java#L305-L306
It looks like you copied the timeSeconds one and forgot to change it.

I think headingAngularVelocityRps should be `The heading angular velocity in rotation/s`, but I'm not sure because English is not my native language and I am a beginner of Swerve Autonomous.

Thank you.

**Comment by mjansen4857** [comment]
This is no longer relevant as the fields in the trajectory state class have changed
