### ISSUE TITLE
Pre-sort rotation targets and event markers

### ISSUE THREAD

**Issue by mjansen4857** [mjansen4857/pathplanner#710]
Sort rotation targets and event markers when saved to the path file, as well as sorting them when paths are created to cover on-the-fly paths. This will make it so that they don't need to be sorted on path point generation and trajectory generation.

**Comment by lidor51** [comment]
Adding a demo-use case to the documentation of event markers + rotation targets to be injected to on-the-fly path would be really appreciated! @mjansen4857
