### ISSUE TITLE
Sorting Method not Being Saved

### ISSUE THREAD

**Issue by JosephTLockwood** [mjansen4857/pathplanner#723]
**Describe the bug**
After applying a sort, changing a setting, and going into and out of a path, the sort method is not saved.

**To Reproduce**
1. Apply a sort method to paths
2. Go into settings
3. Exit and go back into a path and exit
4. Sorting should no longer be applied.

**Expected behavior**
The sort method should be saved and applied until it is changed.

**Comment by mjansen4857** [comment]
I can't seem to reproduce this. Could you give more info on what build you're using and perhaps a screen recording of this behavior?

**Comment by JosephTLockwood** [comment]
I was using PathPlanner-Windows-v0.0.0-dev-871.
[Link](https://drive.google.com/file/d/13Ps4NhljGf7UwJf6uZA7I0f4vl588zc1/view?usp=sharing) to video of the issue.

**Comment by mjansen4857** [comment]
Ok so you're using a build from #705 meaning its a bug with that PR @WindingMotor

**Comment by WindingMotor** [comment]
Very strange Ill take a look at it
