### ISSUE TITLE
No Holonomic Angular Velocity

### ISSUE THREAD

**Issue by roboteer5291** [mjansen4857/pathplanner#79]
While PathPlannerState does include `angularVelocity`, this is in reference to the path itself and not the holonomic rotation of the robot. Adding a term like this for the holonomic rotation would allow holonomic users to improve their robots' abilities to have the proper rotation, as currently the heading would be lagging behind the desired heading at a given point in time. Some swerve users (Not using PathPlanner) have reported that using an angular velocity as a feedforward for their rotation has given them noticeable improvements. Subsequently, adding the holonomic angular velocity to PathPlannerLib would a good next step to take.

**Comment by mjansen4857** [comment]
I plan on including a custom HolonomicDriveController that uses a  rotation feedforward in next year's PPLib release so this will be alongside of it 👍
