### ISSUE TITLE
Center of robot position Output Format

### ISSUE THREAD

**Issue by hamster1147** [mjansen4857/PathPlanner#8]
We use the average of two encoders and a gyro to run our paths. It would be really helpful if we could get the position and velocity of center of the robot.

**Comment by mjansen4857** [comment]
So to clarify, you'd like an option to get a single file with the values representing the whole robot instead of splitting it into left and right paths?

**Comment by hamster1147** [comment]
Correct

**Comment by mjansen4857** [comment]
Just pushed a commit adding this. I'll hold off on releasing until I make sure deploying works properly on Saturday.
