### ISSUE TITLE
Add python install to wiki

### ISSUE THREAD

**Issue by virtuald** [mjansen4857/pathplanner#81]
Wiki doesn't seem to be editable? Here's the link: https://robotpy.readthedocs.io/en/stable/install/pathplannerlib.html

Thanks!

**Comment by mjansen4857** [comment]
Added the link. Thanks for putting this together. Is there any usage documentation yet? I haven't found any. I can link to that as well if you have some.

**Comment by mjansen4857** [comment]
Nevermind I just found it

**Comment by virtuald** [comment]
@TheTripleV put together the initial wrapper around this, not sure if they were planning on translating the wiki for the python documentation page or not. But, it's pretty close to Java usage.

**Comment by mjansen4857** [comment]
Just as an FYI I moved the pathplannerlib code into the main repo instead of a separate repository. I'm not sure if this affects the python library but letting you know just in case.

**Comment by virtuald** [comment]
I just use whatever is published in the sources.zip, so it doesn't matter to me.
