### ISSUE TITLE
Start of the path incorrect 

### ISSUE THREAD

**Issue by Ramtech59Sensei** [mjansen4857/pathplanner#818]
**Describe the bug**
When setting the "Ideal start position" or a "rotation at waypoint"  at the start of the path, the robot always start at zero degrees  

**Expected behavior**
"Ideal start position" should make the robot start at that rotation  and not make the robot rotate as fast as possible to start the path 

**Screenshots**
![test](https://github.com/user-attachments/assets/b91a7b68-695c-41db-b730-b5b491cecae2)

**Comment by mjansen4857** [comment]
After #821 is merged, I will replace the builds on the beta 1 release with the fixed version instead of doing a whole new release. You'll have to redownload the build from there.
