### ISSUE TITLE
Deploying to robot ignores Split Path switch

### ISSUE THREAD

**Issue by hamster1147** [mjansen4857/PathPlanner#9]
Currently deploying to the robot sends both a right and left path no matter which position the split path switch is set to. When generating the path locally, only a source path is generated with the split path turned off, which I assume is working as intended. When deploying to robot, the program seems to ignore the split path switch.

**Comment by mjansen4857** [comment]
Hmm. I thought I made it work for deploying as well. I'll take a look.

**Comment by mjansen4857** [comment]
This should be fixed now. I don't have access to a robot to test it right now so let me know if it still doesn't work.

**Comment by hamster1147** [comment]
Tested it on our robot and it works as intended.

Thanks for fixing these issues so fast. I was able to get our robot to follow the generated paths pretty closely, your tool is so powerful. Thank you for your work.

**Comment by hamster1147** [comment]
So I tested it and it did send the center only file, but it seems the connection to the robot's file system is finicky. I haven't been able to debug it yet, but sometimes I can connect over sftp but not be able to deploy to robot from pathplanner. A lot of the time, but not all of the time, it fails to connect.

**Comment by mjansen4857** [comment]
When you connect to the robot is it the only network connection on your PC, or are you connected to the internet and the robot? I'm not sure what else could cause it to fail if you're connected to the robot. The library I use to deploy uses SFTP so if you can connect with SFTP manually it should be working. I'll have access to some RIOs tomorrow so I will play around with it then.

There is a log file inside of a .PathPlanner folder in your user folder. For windows this would be:
 `C:\Users\<Your User>\.PathPlanner\log.txt`
Errors while connecting should be logged in there. Can you check if there's any connection errors?

**Comment by hamster1147** [comment]
Came back to the shop again, it worked. Don't know why it didn't work before.

**Comment by mjansen4857** [comment]
Interesting. If it fails again see if there are any errors in the log and let me know.

**Comment by hamster1147** [comment]
Roger

**Comment by hamster1147** [comment]
It seems to be doing it again. When I generate the path locally, I only get the one file. When I deploy I get both the left and right file but not the center.

**Comment by mjansen4857** [comment]
I'm looking at the code and it seems like it should be working correctly. I will be able to test it on a robot later today and see if I can reproduce the issue.

**Comment by hamster1147** [comment]
Built the most current version. It is gone.
