### ISSUE TITLE
PathfindingCommand Ends Prematurely

### ISSUE THREAD

**Issue by PickleFace5** [mjansen4857/pathplanner#920]
**Describe the bug**
When Pathfinding to a path, during the PathfindingCommand, the robot will simply stop after a few seconds.

After some digging, it seems to be an issue relating to how the isFinished method for the command is calculated, mainly with the return statement on line 367 (for Python). Upon removing this line, the issue resolves itself, so I believe the implementation of stoppingDistance is incorrect here.

After looking at the same methods in Java and C++, it seems this issue may be present in all languages of PPLib.

**To Reproduce**
1. Run a AutoBuilder.pathfindThenFollowPath command.
2. Observe how it stops early.

**Expected behavior**
The robot is supposed to pathfind without any stopping to the start of the path, then seamlessly execute the path.

**Versions: (please complete the following information):**
 - OS: Windows 11
 - GUI Version: 2025.0.0-beta-5
 - PPLib Version: 2025.0.0b5
 - PPLib Language: Python

**Additional context**
The repository I have used for testing and encountering this bug can be found [here](https://github.com/PickleFace5/2024MetalMelody).

**Comment by mjansen4857** [comment]
This sounds like it’s probably due to path replanning being removed, since the transition between pathfinding and the path depended on it. 

I need to play around with it to see if there’s a way to smooth that transition without replanning.
