### ISSUE TITLE
robotTrackwidth in settings.json is not correct

### ISSUE THREAD

**Issue by mpaulonis** [mjansen4857/pathplanner#942]
After updating to GUI beta 6, my settings.json updated, removing "robottrackWidthMeters": 0.629 and adding "robotTrackwidth": 0.546.  My correct robot track width is 0.629 meters.  My ModuleY values are either 0.314 or -0.314.

I don't know where the 0.546 came from.  I notice that it is the trackwidth in the initial example settings file, which seems suspicious.

I tried manually removing robotTrackwidth from settings.json, and the GUI regenerated it at 0.546.

Not sure if this is an issue or if robotTrackwidth is being used any longer now that the module offsets have been added.  I thought I'd point it out just in case.

 - OS: Windows 10
 - GUI Version: v2025.0.0-beta-6
 - PPLib Version: 2025.0.0-beta-6
 - PPLib Language: Java

**Comment by mjansen4857** [comment]
Track width is only used if not in holonomic mode. This is expected as it will still save each setting anyways.
