### ISSUE TITLE
Beta-6 Target Pose interpolation does not work with alliance flipping

### ISSUE THREAD

**Issue by bhall-ctre** [mjansen4857/pathplanner#945]
**Describe the bug**
When the `shouldFlipPath` boolean supplier returns `true`, the target pose interpolation does not work. The behavior is that PathPlanner appears to be interpolating in the direction of the original unflipped path.

**To Reproduce**
1. Update our [SwerveWithPathPlanner](https://github.com/CrossTheRoadElec/Phoenix6-Examples/tree/41e75b61df5424e8895d5bea3eba8ad7aaa230fa/java/SwerveWithPathPlanner) example to PathPlanner beta-6.
2. In `configureAutoBuilder()`, add a logger for the target pose callback:
```java
var targetPoseLogger = NetworkTableInstance.getDefault().getStructTopic("Target Pose", Pose2d.struct).publish();
PathPlannerLogging.setLogTargetPoseCallback(targetPoseLogger);
```
3. Run the project in simulation.
4. Set the alliance to Blue (while "Disconnected") and run autonomous. Use the AdvantageScope Odometry tab to view the "Target Pose" field (use the Connect to Simulator feature).
5. Set the alliance to Red (while "Disconnected") and re-run autonomous. Use the AdvantageScope Odometry tab to view the "Target Pose", and note the incorrect behavior.

**Expected behavior**
The behavior on the Red alliance should match the Blue alliance, just flipped.

**Screenshots**
Below is a zip with a video of the correct (blue) and incorrect (red) behavior.
[PathPlanner-beta-6-bug.zip](https://github.com/user-attachments/files/18213984/PathPlanner-beta-6-bug.zip)

**Versions: (please complete the following information):**
 - OS: Windows 11
 - GUI Version: n/a
 - PPLib Version: 2025.0.0-beta-6
 - PPLib Language: Java, C++, Python

**Additional context**
This issue was likely introduced with the changes in https://github.com/mjansen4857/pathplanner/pull/935.

**Comment by mjansen4857** [comment]
Yeah, the heading doesn’t get flipped which is now used for interpolation. Oversight on my part. Will try to get fix out asap.
